/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  PwcMultiFilterInterfaces,
} from './components/pwc-multi-filter/PwcMultiFilterInterfaces';
import {
  _filterChangedEventType,
} from './components/pwc-multi-filter/pwc-multi-filter';

export namespace Components {
  interface PwcMultiFilter {
    'addFilter': (config: PwcMultiFilterInterfaces.IFilterTabConfig) => Promise<void>;
    'getFilter': (name: string) => Promise<HTMLPwcFilterElement>;
    'getFilterResult': (name: string) => Promise<object[]>;
    'removeFilter': (name: string) => Promise<void>;
    'subscribeToFilterChange': (name: string, callback: (filterChangedEvent: _filterChangedEventType) => void) => Promise<void>;
  }
}

declare global {


  interface HTMLPwcMultiFilterElement extends Components.PwcMultiFilter, HTMLStencilElement {}
  var HTMLPwcMultiFilterElement: {
    prototype: HTMLPwcMultiFilterElement;
    new (): HTMLPwcMultiFilterElement;
  };
  interface HTMLElementTagNameMap {
    'pwc-multi-filter': HTMLPwcMultiFilterElement;
  }
}

declare namespace LocalJSX {
  interface PwcMultiFilter {}

  interface IntrinsicElements {
    'pwc-multi-filter': PwcMultiFilter;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pwc-multi-filter': LocalJSX.PwcMultiFilter & JSXBase.HTMLAttributes<HTMLPwcMultiFilterElement>;
    }
  }
}


