/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PwcMultiFilter {}
}

declare global {


  interface HTMLPwcMultiFilterElement extends Components.PwcMultiFilter, HTMLStencilElement {}
  var HTMLPwcMultiFilterElement: {
    prototype: HTMLPwcMultiFilterElement;
    new (): HTMLPwcMultiFilterElement;
  };
  interface HTMLElementTagNameMap {
    'pwc-multi-filter': HTMLPwcMultiFilterElement;
  }
}

declare namespace LocalJSX {
  interface PwcMultiFilter {}

  interface IntrinsicElements {
    'pwc-multi-filter': PwcMultiFilter;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pwc-multi-filter': LocalJSX.PwcMultiFilter & JSXBase.HTMLAttributes<HTMLPwcMultiFilterElement>;
    }
  }
}


